# Generated by Django 4.2.25 on 2025-10-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_default_admin_level'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityinvitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communityinvitation',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityinvitation',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='communityinvitation',
            name='inviter',
        ),
        migrations.AlterUniqueTogether(
            name='communityjoinrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communityjoinrequest',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityjoinrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='communityjoinrequest',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='community',
            name='communities_is_acti_c7d0d4_idx',
        ),
        migrations.RemoveField(
            model_name='community',
            name='members_count',
        ),
        migrations.AddField(
            model_name='community',
            name='division',
            field=models.ForeignKey(blank=True, help_text='The geographic division this community belongs to (e.g., municipality, commune). Optional as divisions may change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='core.administrativedivision'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['division', '-created_at'], name='communities_divisio_b2d71e_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['is_active', '-posts_count'], name='communities_is_acti_f75272_idx'),
        ),
        migrations.DeleteModel(
            name='CommunityInvitation',
        ),
        migrations.DeleteModel(
            name='CommunityJoinRequest',
        ),
    ]
