# Generated by Django 4.2.25 on 2025-10-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_post_downvotes_count_post_is_best_post_and_more'),
        ('communities', '0002_add_optional_division_to_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='best_post',
            field=models.ForeignKey(blank=True, help_text='Post marked as best by thread creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_best_post_for', to='content.post'),
        ),
    ]
