# Generated by Django 4.2.25 on 2025-10-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section where this thread belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='communities.section'),
        ),
    ]
