# Generated by Django 4.2.25 on 2025-10-15 21:47

from django.db import migrations
import uuid


def create_default_sections(apps, schema_editor):
    """Create a default 'General' section for each community."""
    Community = apps.get_model('communities', 'Community')
    Section = apps.get_model('communities', 'Section')
    Thread = apps.get_model('communities', 'Thread')

    for community in Community.objects.all():
        # Create default "General" section
        general_section, created = Section.objects.get_or_create(
            community=community,
            slug='general',
            defaults={
                'id': uuid.uuid4(),
                'name': 'General',
                'description': 'General discussions and posts',
                'icon': '💬',
                'order': 0,
                'depth': 0,
                'path': '001',
                'allow_threads': True,
                'allow_direct_posts': True,
                'require_approval': False,
                'is_locked': False,
                'inherit_permissions': True,
            }
        )

        if created:
            # Assign all existing threads without section to "General"
            threads_updated = Thread.objects.filter(
                community=community,
                section__isnull=True
            ).update(section=general_section)

            # Update section counter
            general_section.threads_count = threads_updated
            general_section.total_threads_count = threads_updated
            general_section.save(update_fields=[
                'threads_count',
                'total_threads_count'
            ])


def reverse_default_sections(apps, schema_editor):
    """Remove default 'General' sections (set threads.section to null)."""
    Thread = apps.get_model('communities', 'Thread')
    Section = apps.get_model('communities', 'Section')

    # Set all threads in "General" sections back to null
    Thread.objects.filter(section__slug='general').update(section=None)

    # Delete all "General" sections
    Section.objects.filter(slug='general').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_thread_section'),
    ]

    operations = [
        migrations.RunPython(
            create_default_sections,
            reverse_default_sections
        ),
    ]
