# Generated by Django 4.2.25 on 2025-10-16 00:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_create_default_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriqueTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('actualites', 'Actualités'), ('evenements', 'Événements'), ('commerces', 'Commerces'), ('services', 'Services'), ('aide', 'Aide & Support'), ('emploi', 'Emploi'), ('logement', 'Logement'), ('transport', 'Transport'), ('sante', 'Santé'), ('education', 'Éducation'), ('loisirs', 'Loisirs'), ('annonces', 'Petites Annonces'), ('custom', 'Custom')], help_text='Type of rubrique template', max_length=50, unique=True)),
                ('default_name', models.CharField(help_text='Default French name for this rubrique', max_length=100)),
                ('default_name_en', models.CharField(blank=True, help_text='Default English name', max_length=100)),
                ('default_description', models.TextField(blank=True, help_text='Default description template', max_length=500)),
                ('default_icon', models.CharField(blank=True, help_text='Default icon (emoji or icon class)', max_length=50)),
                ('default_color', models.CharField(blank=True, default='#6366f1', help_text='Default color (hex code)', max_length=7)),
                ('is_required', models.BooleanField(default=False, help_text='Auto-create for all new communities')),
                ('allow_customization', models.BooleanField(default=True, help_text='Allow communities to customize name/icon/color')),
                ('allow_threads', models.BooleanField(default=True, help_text='Allow creating threads in this rubrique')),
                ('allow_direct_posts', models.BooleanField(default=False, help_text='Allow posts without threads')),
                ('supports_subsections', models.BooleanField(default=True, help_text='Allow creating sub-sections')),
                ('recommended_subsections', models.JSONField(blank=True, default=list, help_text='Recommended subsection template types (JSON array)')),
                ('default_order', models.PositiveIntegerField(default=0, help_text='Default display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Template is active and available for use')),
            ],
            options={
                'verbose_name': 'Rubrique Template',
                'verbose_name_plural': 'Rubrique Templates',
                'db_table': 'rubrique_templates',
                'ordering': ['default_order', 'default_name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='True if community customized this template-based section'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_template_based',
            field=models.BooleanField(default=False, help_text='True if created from a rubrique template'),
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this section was created from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='communities.rubriquetemplate'),
        ),
    ]
