# Generated by Django 4.2.25 on 2025-10-16 00:38

from django.db import migrations
import uuid


def create_default_rubrique_templates(apps, schema_editor):
    """Create hierarchical rubrique templates matching frontend Sidebar.js.

    Creates a global hierarchical tree with main rubriques and subsections.
    Communities select which ones to enable via Community.enabled_rubriques.
    """
    RubriqueTemplate = apps.get_model('communities', 'RubriqueTemplate')

    # Store created rubriques by template_type for parent references
    created_rubriques = {}

    # MAIN RUBRIQUES (depth=0, parent=None)
    main_rubriques = [
        # REQUIRED MAIN RUBRIQUES
        {
            'template_type': 'actualites',
            'default_name': 'Actualités',
            'default_name_en': 'News',
            'default_description': 'Actualités locales',
            'default_icon': 'LocationCity',
            'default_color': '#3B82F6',
            'is_required': True,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 1,
        },
        {
            'template_type': 'evenements',
            'default_name': 'Événements',
            'default_name_en': 'Events',
            'default_description': 'Événements et festivités',
            'default_icon': 'Event',
            'default_color': '#8B5CF6',
            'is_required': True,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 2,
        },
        {
            'template_type': 'commerces',
            'default_name': 'Commerces',
            'default_name_en': 'Businesses',
            'default_description': 'Commerce local',
            'default_icon': 'Business',
            'default_color': '#10B981',
            'is_required': True,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 3,
        },
        # OPTIONAL MAIN RUBRIQUES
        {
            'template_type': 'transport',
            'default_name': 'Transport',
            'default_name_en': 'Transportation',
            'default_description': 'Transport et circulation',
            'default_icon': 'DirectionsBus',
            'default_color': '#F59E0B',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 4,
        },
        {
            'template_type': 'art',
            'default_name': 'Art',
            'default_name_en': 'Art',
            'default_description': 'Créations artistiques',
            'default_icon': 'Palette',
            'default_color': '#EC4899',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 5,
        },
        {
            'template_type': 'litterature',
            'default_name': 'Littérature',
            'default_name_en': 'Literature',
            'default_description': 'Œuvres littéraires',
            'default_icon': 'MenuBook',
            'default_color': '#6366F1',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 6,
        },
        {
            'template_type': 'poesie',
            'default_name': 'Poésie',
            'default_name_en': 'Poetry',
            'default_description': 'Poèmes et vers',
            'default_icon': 'Create',
            'default_color': '#A855F7',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 7,
        },
        {
            'template_type': 'photographie',
            'default_name': 'Photographie',
            'default_name_en': 'Photography',
            'default_description': 'Images et captures',
            'default_icon': 'PhotoCamera',
            'default_color': '#14B8A6',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 8,
        },
        {
            'template_type': 'histoire',
            'default_name': 'Histoire',
            'default_name_en': 'History',
            'default_description': 'Patrimoine local',
            'default_icon': 'History',
            'default_color': '#F97316',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 9,
        },
        {
            'template_type': 'sport',
            'default_name': 'Sport',
            'default_name_en': 'Sports',
            'default_description': 'Activités sportives',
            'default_icon': 'Sports',
            'default_color': '#EF4444',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 10,
        },
        {
            'template_type': 'culture',
            'default_name': 'Culture',
            'default_name_en': 'Culture',
            'default_description': 'Événements culturels',
            'default_icon': 'TheaterComedy',
            'default_color': '#8B5CF6',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 11,
        },
        {
            'template_type': 'reconnaissance',
            'default_name': 'Reconnaissance',
            'default_name_en': 'Recognition',
            'default_description': 'Valorisation communautaire',
            'default_icon': 'EmojiEvents',
            'default_color': '#FBBF24',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 12,
        },
        {
            'template_type': 'chronologie',
            'default_name': 'Chronologie',
            'default_name_en': 'Timeline',
            'default_description': 'Timeline des événements',
            'default_icon': 'Timeline',
            'default_color': '#06B6D4',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 13,
        },
    ]

    # Create main rubriques (depth=0, parent=None)
    for rubrique_data in main_rubriques:
        rubrique_data['id'] = uuid.uuid4()
        rubrique_data['parent_id'] = None
        rubrique_data['depth'] = 0
        rubrique_data['path'] = str(rubrique_data['default_order']).zfill(3)
        rubrique = RubriqueTemplate.objects.create(**rubrique_data)
        created_rubriques[rubrique_data['template_type']] = rubrique

    # SUBSECTIONS (depth=1+, with parent references)
    subsections = [
        # Événements subsections
        {
            'parent_type': 'evenements',
            'template_type': 'evenements_concerts',
            'default_name': 'Concerts',
            'default_name_en': 'Concerts',
            'default_description': 'Concerts et spectacles musicaux',
            'default_icon': 'MusicNote',
            'default_color': '#8B5CF6',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 1,
        },
        {
            'parent_type': 'evenements',
            'template_type': 'evenements_festivals',
            'default_name': 'Festivals',
            'default_name_en': 'Festivals',
            'default_description': 'Festivals et célébrations',
            'default_icon': 'Festival',
            'default_color': '#8B5CF6',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 2,
        },
        # Sport subsections
        {
            'parent_type': 'sport',
            'template_type': 'sport_hockey',
            'default_name': 'Hockey',
            'default_name_en': 'Hockey',
            'default_description': 'Hockey sur glace',
            'default_icon': 'SportsHockey',
            'default_color': '#EF4444',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 1,
        },
        {
            'parent_type': 'sport',
            'template_type': 'sport_soccer',
            'default_name': 'Soccer',
            'default_name_en': 'Soccer',
            'default_description': 'Football',
            'default_icon': 'SportsSoccer',
            'default_color': '#EF4444',
            'is_required': False,
            'allow_threads': True,
            'allow_direct_posts': False,
            'default_order': 2,
        },
    ]

    # Create subsections (depth=1, with parent)
    for subsection_data in subsections:
        parent_type = subsection_data.pop('parent_type')
        parent = created_rubriques.get(parent_type)

        if parent:
            subsection_data['id'] = uuid.uuid4()
            subsection_data['parent_id'] = parent.id
            subsection_data['depth'] = 1
            parent_path = str(parent.default_order).zfill(3)
            subsection_data['path'] = (
                f"{parent_path}.{str(subsection_data['default_order']).zfill(3)}"
            )
            RubriqueTemplate.objects.create(**subsection_data)


def reverse_create_templates(apps, schema_editor):
    """Remove all rubrique templates."""
    RubriqueTemplate = apps.get_model('communities', 'RubriqueTemplate')
    RubriqueTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_add_rubrique_templates'),
    ]

    operations = [
        migrations.RunPython(
            create_default_rubrique_templates,
            reverse_create_templates
        ),
    ]
