# Generated by Django 4.2.25 on 2025-10-16 13:13

import communities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_create_default_rubrique_templates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='community',
        ),
        migrations.RemoveField(
            model_name='section',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='section',
            name='parent_section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='template',
        ),
        migrations.AlterModelOptions(
            name='rubriquetemplate',
            options={'ordering': ['parent__default_order', 'default_order', 'default_name'], 'verbose_name': 'Rubrique Template', 'verbose_name_plural': 'Rubrique Templates'},
        ),
        migrations.RemoveField(
            model_name='rubriquetemplate',
            name='allow_customization',
        ),
        migrations.RemoveField(
            model_name='rubriquetemplate',
            name='recommended_subsections',
        ),
        migrations.RemoveField(
            model_name='rubriquetemplate',
            name='supports_subsections',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='section',
        ),
        migrations.AddField(
            model_name='community',
            name='enabled_rubriques',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled rubrique template IDs (UUIDs as strings)'),
        ),
        migrations.AddField(
            model_name='rubriquetemplate',
            name='depth',
            field=models.PositiveIntegerField(default=0, help_text='0=top-level, 1=subsection, 2=sub-subsection, etc.'),
        ),
        migrations.AddField(
            model_name='rubriquetemplate',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent rubrique (null for top-level rubriques)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='communities.rubriquetemplate'),
        ),
        migrations.AddField(
            model_name='rubriquetemplate',
            name='path',
            field=models.CharField(blank=True, help_text="Materialized path (e.g., '001.002.003')", max_length=500),
        ),
        migrations.AddField(
            model_name='thread',
            name='rubrique_template',
            field=models.ForeignKey(default=communities.models.get_default_rubrique_template, help_text='Rubrique category for this thread (REQUIRED)', on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='communities.rubriquetemplate'),
        ),
        migrations.AlterField(
            model_name='rubriquetemplate',
            name='default_icon',
            field=models.CharField(blank=True, help_text='Default icon (MUI icon name)', max_length=50),
        ),
        migrations.AlterField(
            model_name='rubriquetemplate',
            name='default_order',
            field=models.PositiveIntegerField(default=0, help_text='Default display order within parent or at root level'),
        ),
        migrations.AlterField(
            model_name='rubriquetemplate',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Auto-enable for all new communities'),
        ),
        migrations.AlterField(
            model_name='rubriquetemplate',
            name='template_type',
            field=models.CharField(help_text="Unique code (e.g., 'actualites', 'evenements_sports_hockey')", max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='rubriquetemplate',
            index=models.Index(fields=['parent', 'default_order'], name='rubrique_te_parent__ca74c2_idx'),
        ),
        migrations.AddIndex(
            model_name='rubriquetemplate',
            index=models.Index(fields=['depth'], name='rubrique_te_depth_06c713_idx'),
        ),
        migrations.AddIndex(
            model_name='rubriquetemplate',
            index=models.Index(fields=['path'], name='rubrique_te_path_2d649f_idx'),
        ),
    ]
