# Generated by Django 4.2.25 on 2025-10-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_post_section_post_rubrique_template'),
        ('communities', '0009_alter_section_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
