# Generated by Django 4.2.25 on 2025-10-16 13:25

from django.db import migrations


def update_rubrique_hierarchy(apps, schema_editor):
    """Update rubrique templates with new hierarchy."""
    RubriqueTemplate = apps.get_model('communities', 'RubriqueTemplate')

    # Delete all existing rubriques
    RubriqueTemplate.objects.all().delete()

    # Create main rubriques (depth=0, parent=None)
    rubriques = {}

    # Required rubriques
    rubriques['actualites'] = RubriqueTemplate.objects.create(
        template_type='actualites',
        default_name='Actualités',
        default_name_en='News',
        default_description='Actualités et informations locales',
        default_icon='📰',
        default_color='#3b82f6',
        is_required=True,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=1,
        parent=None,
        depth=0,
        path='001'
    )

    rubriques['evenements'] = RubriqueTemplate.objects.create(
        template_type='evenements',
        default_name='Événements',
        default_name_en='Events',
        default_description='Événements locaux, concerts, festivals',
        default_icon='🎭',
        default_color='#8b5cf6',
        is_required=True,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=2,
        parent=None,
        depth=0,
        path='002'
    )

    rubriques['commerces'] = RubriqueTemplate.objects.create(
        template_type='commerces',
        default_name='Commerces',
        default_name_en='Businesses',
        default_description='Commerces et services locaux',
        default_icon='🏪',
        default_color='#10b981',
        is_required=True,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=3,
        parent=None,
        depth=0,
        path='003'
    )

    # Optional rubriques
    rubriques['transport'] = RubriqueTemplate.objects.create(
        template_type='transport',
        default_name='Transport',
        default_name_en='Transportation',
        default_description='Informations sur les transports',
        default_icon='🚌',
        default_color='#f59e0b',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=4,
        parent=None,
        depth=0,
        path='004'
    )

    rubriques['art'] = RubriqueTemplate.objects.create(
        template_type='art',
        default_name='Art',
        default_name_en='Art',
        default_description='Arts et culture',
        default_icon='🎨',
        default_color='#ec4899',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=5,
        parent=None,
        depth=0,
        path='005'
    )

    rubriques['litterature'] = RubriqueTemplate.objects.create(
        template_type='litterature',
        default_name='Littérature',
        default_name_en='Literature',
        default_description='Livres et littérature',
        default_icon='📚',
        default_color='#6366f1',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=6,
        parent=None,
        depth=0,
        path='006'
    )

    rubriques['poesie'] = RubriqueTemplate.objects.create(
        template_type='poesie',
        default_name='Poésie',
        default_name_en='Poetry',
        default_description='Poésie et vers',
        default_icon='✍️',
        default_color='#8b5cf6',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=7,
        parent=None,
        depth=0,
        path='007'
    )

    rubriques['photographie'] = RubriqueTemplate.objects.create(
        template_type='photographie',
        default_name='Photographie',
        default_name_en='Photography',
        default_description='Photos et photographie',
        default_icon='📷',
        default_color='#06b6d4',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=8,
        parent=None,
        depth=0,
        path='008'
    )

    rubriques['histoire'] = RubriqueTemplate.objects.create(
        template_type='histoire',
        default_name='Histoire',
        default_name_en='History',
        default_description='Histoire locale',
        default_icon='📜',
        default_color='#78716c',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=9,
        parent=None,
        depth=0,
        path='009'
    )

    rubriques['sport'] = RubriqueTemplate.objects.create(
        template_type='sport',
        default_name='Sport',
        default_name_en='Sports',
        default_description='Sports et activités sportives',
        default_icon='⚽',
        default_color='#ef4444',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=10,
        parent=None,
        depth=0,
        path='010'
    )

    rubriques['culture'] = RubriqueTemplate.objects.create(
        template_type='culture',
        default_name='Culture',
        default_name_en='Culture',
        default_description='Culture et patrimoine',
        default_icon='🏛️',
        default_color='#a855f7',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=11,
        parent=None,
        depth=0,
        path='011'
    )

    rubriques['reconnaissance'] = RubriqueTemplate.objects.create(
        template_type='reconnaissance',
        default_name='Reconnaissance',
        default_name_en='Recognition',
        default_description='Reconnaissance et hommages',
        default_icon='🏆',
        default_color='#fbbf24',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=12,
        parent=None,
        depth=0,
        path='012'
    )

    rubriques['chronologie'] = RubriqueTemplate.objects.create(
        template_type='chronologie',
        default_name='Chronologie',
        default_name_en='Timeline',
        default_description='Chronologie des événements',
        default_icon='⏰',
        default_color='#64748b',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=13,
        parent=None,
        depth=0,
        path='013'
    )

    # Create subsections (depth=1, with parent)
    RubriqueTemplate.objects.create(
        template_type='evenements_concerts',
        default_name='Concerts',
        default_name_en='Concerts',
        default_description='Concerts et spectacles musicaux',
        default_icon='🎵',
        default_color='#8b5cf6',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=1,
        parent=rubriques['evenements'],
        depth=1,
        path='002.001'
    )

    RubriqueTemplate.objects.create(
        template_type='evenements_festivals',
        default_name='Festivals',
        default_name_en='Festivals',
        default_description='Festivals et événements culturels',
        default_icon='🎪',
        default_color='#8b5cf6',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=2,
        parent=rubriques['evenements'],
        depth=1,
        path='002.002'
    )

    RubriqueTemplate.objects.create(
        template_type='sport_hockey',
        default_name='Hockey',
        default_name_en='Hockey',
        default_description='Hockey sur glace',
        default_icon='🏒',
        default_color='#ef4444',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=1,
        parent=rubriques['sport'],
        depth=1,
        path='010.001'
    )

    RubriqueTemplate.objects.create(
        template_type='sport_soccer',
        default_name='Soccer',
        default_name_en='Soccer',
        default_description='Football/Soccer',
        default_icon='⚽',
        default_color='#ef4444',
        is_required=False,
        allow_threads=True,
        allow_direct_posts=True,
        default_order=2,
        parent=rubriques['sport'],
        depth=1,
        path='010.002'
    )


def reverse_update(apps, schema_editor):
    """Reverse the hierarchy update (not really needed)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_delete_section'),
    ]

    operations = [
        migrations.RunPython(update_rubrique_hierarchy, reverse_update),
    ]
