# Generated by Django 4.2.24 on 2025-09-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='boundary_type',
            field=models.CharField(blank=True, help_text='Dynamic boundary type (country-specific)', max_length=50),
        ),
    ]
