# Generated by Django 4.2.24 on 2025-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allow_dynamic_boundary_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='default_admin_level',
            field=models.IntegerField(blank=True, help_text='Primary admin level (3=communes, 4=municipalities)', null=True),
        ),
    ]
