# Generated by Django 4.2.25 on 2025-10-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_default_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, help_text="Unicode flag emoji (e.g., '🇧🇯', '🇨🇦', '🇫🇷')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text="International dialing code (e.g., '+229', '+1', '+33')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, db_index=True, help_text="Geographic region (e.g., 'West Africa', 'North America', 'Western Europe')", max_length=50, null=True),
        ),
    ]
