# Generated by Django 4.2.25 on 2025-10-10 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_redundant_fields_from_community_analytics'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('url_name', models.CharField(blank=True, help_text='Django URL name if available', max_length=100)),
                ('page_type', models.CharField(choices=[('home', 'Homepage'), ('community', 'Community Page'), ('post', 'Post Detail'), ('profile', 'User Profile'), ('search', 'Search Results'), ('about', 'About/Info Page'), ('auth', 'Login/Signup Page'), ('other', 'Other')], db_index=True, max_length=50)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on this page in seconds')),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('is_entry_page', models.BooleanField(default=False, help_text='First page in the session')),
                ('is_exit_page', models.BooleanField(default=False, help_text='Last page in the session')),
                ('scroll_depth', models.PositiveSmallIntegerField(default=0, help_text='Percentage of page scrolled (0-100)')),
                ('interactions', models.PositiveIntegerField(default=0, help_text='Number of clicks, hovers, etc.')),
                ('content_id', models.UUIDField(blank=True, help_text='ID of viewed content (post, community, etc.)', null=True)),
                ('content_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, help_text='Device fingerprint hash for anonymous identification', max_length=128)),
                ('session_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pages_visited', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total session duration in seconds')),
                ('landing_page', models.URLField(max_length=500)),
                ('exit_page', models.URLField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('converted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_bot', models.BooleanField(default=False, help_text='Flagged as bot based on behavior patterns')),
                ('bot_score', models.FloatField(default=0.0, help_text='Bot likelihood score 0-1 (1 = definitely bot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='PageAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_path', models.CharField(db_index=True, max_length=500)),
                ('page_type', models.CharField(choices=[('home', 'Homepage'), ('community', 'Community Page'), ('post', 'Post Detail'), ('profile', 'User Profile'), ('search', 'Search Results'), ('about', 'About/Info Page'), ('auth', 'Login/Signup Page'), ('other', 'Other')], db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('authenticated_views', models.PositiveIntegerField(default=0)),
                ('anonymous_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0, help_text='Unique device fingerprints')),
                ('avg_time_on_page', models.FloatField(default=0.0, help_text='Average time in seconds')),
                ('avg_scroll_depth', models.FloatField(default=0.0, help_text='Average scroll percentage')),
                ('avg_interactions', models.FloatField(default=0.0)),
                ('mobile_views', models.PositiveIntegerField(default=0)),
                ('desktop_views', models.PositiveIntegerField(default=0)),
                ('tablet_views', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(blank=True, default=list, help_text="List of dicts: [{'country': 'US', 'count': 100}, ...]")),
                ('top_referrers', models.JSONField(blank=True, default=list, help_text='Top referring URLs')),
                ('bounce_count', models.PositiveIntegerField(default=0, help_text='Views where user left immediately')),
                ('exit_count', models.PositiveIntegerField(default=0, help_text='Views where user ended session on this page')),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('exit_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-total_views'],
            },
        ),
        migrations.RemoveIndex(
            model_name='communityanalytics',
            name='analytics_c_communi_d7a305_idx',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='current_online_members',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='daily_active_members',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='monthly_active_members',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='peak_online_this_month',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='peak_online_this_week',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='peak_online_today',
        ),
        migrations.RemoveField(
            model_name='communityanalytics',
            name='weekly_active_members',
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='cross_division_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of cross-division visits'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='cross_division_visits',
            field=models.PositiveIntegerField(default=0, help_text='Count of visitors from different divisions'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='current_anonymous_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Current anonymous visitors'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='current_authenticated_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Current authenticated visitors'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='current_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Total current visitors (auth + anonymous)'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='daily_anonymous_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='daily_authenticated_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='daily_unique_visitors',
            field=models.PositiveIntegerField(default=0, help_text='Unique visitors today (by fingerprint/user_id)'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='monthly_unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='peak_visitors_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='peak_visitors_this_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='peak_visitors_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='visitor_divisions',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of division_id: visitor_count'),
        ),
        migrations.AddField(
            model_name='communityanalytics',
            name='weekly_unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='communityanalytics',
            index=models.Index(fields=['community', 'current_visitors'], name='analytics_c_communi_4dab70_idx'),
        ),
        migrations.AddIndex(
            model_name='communityanalytics',
            index=models.Index(fields=['community', '-daily_unique_visitors'], name='analytics_c_communi_ad8e89_idx'),
        ),
        migrations.AddIndex(
            model_name='communityanalytics',
            index=models.Index(fields=['-cross_division_visits'], name='analytics_c_cross_d_335723_idx'),
        ),
        migrations.AddIndex(
            model_name='pageanalytics',
            index=models.Index(fields=['-date', 'page_type'], name='analytics_p_date_2fb33b_idx'),
        ),
        migrations.AddIndex(
            model_name='pageanalytics',
            index=models.Index(fields=['url_path', '-date'], name='analytics_p_url_pat_d10eda_idx'),
        ),
        migrations.AddIndex(
            model_name='pageanalytics',
            index=models.Index(fields=['-total_views'], name='analytics_p_total_v_c2a764_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageanalytics',
            unique_together={('url_path', 'date')},
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='converted_to_user',
            field=models.ForeignKey(blank=True, help_text='Links to user account if anonymous visitor signed up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_anonymous', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='anonymouspageview',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.anonymoussession'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['device_fingerprint', '-session_start'], name='analytics_a_device__b32d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['is_active', '-session_start'], name='analytics_a_is_acti_ef88dc_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['converted_to_user', '-converted_at'], name='analytics_a_convert_e91c67_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['-session_start'], name='analytics_a_session_18935b_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['utm_source', '-session_start'], name='analytics_a_utm_sou_de2548_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['country', '-session_start'], name='analytics_a_country_d8eda2_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymouspageview',
            index=models.Index(fields=['session', '-viewed_at'], name='analytics_a_session_7f68ef_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymouspageview',
            index=models.Index(fields=['page_type', '-viewed_at'], name='analytics_a_page_ty_4c2a54_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymouspageview',
            index=models.Index(fields=['-viewed_at'], name='analytics_a_viewed__db28b5_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymouspageview',
            index=models.Index(fields=['content_id', 'content_type'], name='analytics_a_content_dfd3c1_idx'),
        ),
    ]
