# Generated by Django 4.2.25 on 2025-10-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='administrative_division',
            field=models.ForeignKey(blank=True, help_text='User administrative division (city/municipality)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.administrativedivision'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.usersession'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_about_me', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_events', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='accounts.badgedefinition'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.supportticket'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='moderatorprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_profile', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='contactchangerequest',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_change_requests', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='contactchangelog',
            name='change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.contactchangerequest'),
        ),
        migrations.AddField(
            model_name='commercialprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='block',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='badgedefinition',
            index=models.Index(fields=['is_active'], name='accounts_ba_is_acti_299323_idx'),
        ),
        migrations.AddIndex(
            model_name='badgedefinition',
            index=models.Index(fields=['code'], name='accounts_ba_code_01cc4f_idx'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-started_at'], name='accounts_us_user_id_9b48aa_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_3fa67a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', '-started_at'], name='accounts_us_is_acti_b6a8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device_fingerprint'], name='accounts_us_device__63efeb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'fast_fingerprint', 'is_active'], name='accounts_us_user_id_bef384_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='accounts_us_user_id_806298_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='accounts_us_role_e16858_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_verified'], name='accounts_us_is_veri_40a50a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_suspended'], name='accounts_us_is_susp_bec9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['administrative_division'], name='accounts_us_adminis_68e51e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-last_active'], name='accounts_us_last_ac_224c87_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['polls_created_count'], name='accounts_us_polls_c_254d40_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['poll_votes_count'], name='accounts_us_poll_vo_f1f4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['reposts_count'], name='accounts_us_reposts_0d5e02_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['shares_sent_count'], name='accounts_us_shares__2d0e89_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['shares_received_count'], name='accounts_us_shares__c64bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['best_comments_count'], name='accounts_us_best_co_eab799_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['communities_joined_count'], name='accounts_us_communi_5b6181_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['registration_index'], name='accounts_us_registr_9ed928_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_a02681_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', '-created_at'], name='accounts_us_event_t_6b7ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['target_user', '-created_at'], name='accounts_us_target__13dfb0_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['severity', '-created_at'], name='accounts_us_severit_4fb526_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['success', '-created_at'], name='accounts_us_success_9ef62c_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['requires_review', '-created_at'], name='accounts_us_require_f480db_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['profile', '-earned_at'], name='accounts_us_profile_9f591f_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge'], name='accounts_us_badge_i_b7f024_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('profile', 'badge')},
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='accounts_su_status_cf2be4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', '-created_at'], name='accounts_su_assigne_0bab8a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', '-created_at'], name='accounts_su_user_id_c26358_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='accounts_su_ticket__c1b8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='accounts_su_ticket__205d54_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender', '-created_at'], name='accounts_su_sender__777f58_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['message_type'], name='accounts_su_message_2d1265_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['profile'], name='accounts_pr_profile_b8fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['is_verified'], name='accounts_pr_is_veri_675b70_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['profile'], name='accounts_mo_profile_1c5cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['moderator_level'], name='accounts_mo_moderat_63bce6_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['specialization'], name='accounts_mo_special_fc87bd_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['is_active', 'is_available'], name='accounts_mo_is_acti_b900b0_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['-last_action_date'], name='accounts_mo_last_ac_b8f25f_idx'),
        ),
        migrations.AddIndex(
            model_name='moderatorprofile',
            index=models.Index(fields=['accuracy_score'], name='accounts_mo_accurac_94d34b_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'created_at'], name='accounts_fo_followe_6d6ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', 'created_at'], name='accounts_fo_followe_4ce64c_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['status', 'created_at'], name='accounts_fo_status_8f4b32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
        migrations.AddIndex(
            model_name='contactchangerequest',
            index=models.Index(fields=['user_profile', 'status'], name='accounts_co_user_pr_0f7bad_idx'),
        ),
        migrations.AddIndex(
            model_name='contactchangerequest',
            index=models.Index(fields=['change_type', 'status'], name='accounts_co_change__7916b4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactchangerequest',
            index=models.Index(fields=['expires_at'], name='accounts_co_expires_c70ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactchangelog',
            index=models.Index(fields=['change_request', 'created_at'], name='accounts_co_change__1f3ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='contactchangelog',
            index=models.Index(fields=['action_type', 'created_at'], name='accounts_co_action__15bd00_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprofile',
            index=models.Index(fields=['profile'], name='accounts_co_profile_5c0b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprofile',
            index=models.Index(fields=['business_type'], name='accounts_co_busines_e25429_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprofile',
            index=models.Index(fields=['is_verified'], name='accounts_co_is_veri_1ad18a_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprofile',
            index=models.Index(fields=['subscription_plan'], name='accounts_co_subscri_1e9871_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprofile',
            index=models.Index(fields=['trust_score'], name='accounts_co_trust_s_eae46e_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialprofile',
            index=models.Index(fields=['customer_rating'], name='accounts_co_custome_33eac2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['profile'], name='accounts_ad_profile_f0e2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['admin_level'], name='accounts_ad_admin_l_fc4445_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['is_active'], name='accounts_ad_is_acti_673532_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['access_level'], name='accounts_ad_access__971560_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['-last_admin_action'], name='accounts_ad_last_ad_fd7e77_idx'),
        ),
    ]
