# Generated by Django 4.2.24 on 2025-09-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_us_city_id_1ef302_idx',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='administrative_division',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['administrative_division'], name='accounts_us_adminis_68e51e_idx'),
        ),
    ]
