# Generated by Django 4.2.24 on 2025-10-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_city_to_administrative_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accept_terms',
            field=models.BooleanField(default=False, help_text='User has accepted terms and conditions during registration'),
        ),
    ]
