# Generated by Django 4.2.24 on 2025-10-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_accept_terms_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_us_country_ef6b59_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
