# Generated by Django 4.2.25 on 2025-10-14 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import messaging.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_rooms/')),
                ('is_private', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to='accounts.userprofile')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('location', 'Location'), ('system', 'System')], default='text', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=messaging.models.Message.image_upload_to)),
                ('video', models.FileField(blank=True, null=True, upload_to=messaging.models.Message.video_upload_to)),
                ('audio', models.FileField(blank=True, null=True, upload_to=messaging.models.Message.audio_upload_to)),
                ('file', models.FileField(blank=True, null=True, upload_to=messaging.models.Message.file_upload_to)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forward_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='messaging.message')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to='accounts.userprofile')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline'), ('invisible', 'Invisible')], default='offline', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('custom_status', models.CharField(blank=True, max_length=100)),
                ('status_emoji', models.CharField(blank=True, max_length=10)),
                ('away_since', models.DateTimeField(blank=True, null=True)),
                ('total_online_time', models.DurationField(default=datetime.timedelta)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-last_seen'], name='messaging_u_status_314d92_idx'), models.Index(fields=['-last_seen'], name='messaging_u_last_se_b816e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-read_at'], name='messaging_m_user_id_199543_idx'), models.Index(fields=['message', 'user'], name='messaging_m_message_7583fc_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'emoji'], name='messaging_m_message_5250bc_idx'), models.Index(fields=['user', '-created_at'], name='messaging_m_user_id_53f481_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='messaging_m_room_id_3d58b2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='messaging_m_sender__9b0bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to', '-created_at'], name='messaging_m_reply_t_cecef8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_pinned', '-created_at'], name='messaging_m_is_pinn_1e4083_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', '-updated_at'], name='messaging_c_room_ty_4d7d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by', '-created_at'], name='messaging_c_created_be8026_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_archived', '-last_activity'], name='messaging_c_is_arch_dbd262_idx'),
        ),
    ]
