// Default community media constants
// These can be used when community media access is restricted or not available

export const DEFAULT_COVER_IMAGE = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDgwMCA0MDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI4MDAiIGhlaWdodD0iNDAwIiBmaWxsPSIjZjNmNGY2Ii8+CjxwYXRoIGQ9Im0yMzEgMzAwIDY5LTY2IDI3IDI2IDEyMS0xMTYgMTQyIDEzNnYtMTgwaDIwMHYyMDBIMjMxeiIgZmlsbD0iI2U1ZTdlYiIvPgo8Y2lyY2xlIGN4PSIzMzgiIGN5PSIxNjgiIHI9IjUwIiBmaWxsPSIjZTVlN2ViIi8+Cjwvc3ZnPgo=";

export const DEFAULT_AVATAR_IMAGE = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgY3g9IjEwMCIgY3k9IjEwMCIgcj0iMTAwIiBmaWxsPSIjZjNmNGY2Ii8+CjxwYXRoIGQ9Ik0xMDAgMTEwYTMwIDMwIDAgMSAwIDAtNjAgMzAgMzAgMCAwIDAgMCA2MFpNMTAwIDEzMGMtMzMuMTM3IDAtNjAgMTcuOTA5LTYwIDQwaDEyMGMwLTIyLjA5MS0yNi44NjMtNDAtNjAtNDBaIiBmaWxsPSIjZTVlN2ViIi8+Cjwvc3ZnPgo=";

export const RESTRICTED_COVER_MESSAGE = "🔒 Join to view community cover";
export const RESTRICTED_AVATAR_MESSAGE = "🔒 Join to view community avatar";
