# Generated by Django 4.2.24 on 2025-09-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('post', 'Post'), ('user', 'User'), ('community', 'Community'), ('message', 'Message'), ('poll', 'Poll'), ('other', 'Other')], default='other', max_length=50)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'search_type', 'created_at'], name='search_user_user_id_a6491e_idx'), models.Index(fields=['query'], name='search_user_query_9a1f76_idx')],
            },
        ),
    ]
