# Generated by Django 4.2.25 on 2025-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description/caption for this media attachment', max_length=200),
        ),
    ]
