# Generated by Django 4.2.25 on 2025-10-13 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_redundant_fields_from_community_analytics'),
        ('content', '0002_add_postmedia_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('care', '🤗 Care'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('yay', '🎉 Yay'), ('clap', '👏 Clap'), ('fire', '🔥 Fire'), ('star', '⭐ Star'), ('party', '🥳 Party'), ('heart_eyes', '😍 Heart Eyes'), ('pray', '🙏 Pray'), ('strong', '💪 Strong'), ('celebrate', '🎊 Celebrate'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('worried', '😟 Worried'), ('disappointed', '😞 Disappointed'), ('thinking', '🤔 Thinking'), ('curious', '🧐 Curious'), ('shock', '😱 Shock'), ('confused', '😕 Confused')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'reaction_type'], name='content_pos_post_id_e4c3d0_idx'), models.Index(fields=['user', 'created_at'], name='content_pos_user_id_61d6e4_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('care', '🤗 Care'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('yay', '🎉 Yay'), ('clap', '👏 Clap'), ('fire', '🔥 Fire'), ('star', '⭐ Star'), ('party', '🥳 Party'), ('heart_eyes', '😍 Heart Eyes'), ('pray', '🙏 Pray'), ('strong', '💪 Strong'), ('celebrate', '🎊 Celebrate'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('worried', '😟 Worried'), ('disappointed', '😞 Disappointed'), ('thinking', '🤔 Thinking'), ('curious', '🧐 Curious'), ('shock', '😱 Shock'), ('confused', '😕 Confused')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='content.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', 'reaction_type'], name='content_com_comment_5fb2e7_idx'), models.Index(fields=['user', 'created_at'], name='content_com_user_id_59e547_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
