# Generated by Django 4.2.25 on 2025-10-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_postreaction_commentreaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
