# Generated by Django 4.2.25 on 2025-10-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_like_unique_together_remove_like_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('link', 'Link'), ('poll', 'Poll'), ('repost', 'Simple Repost'), ('repost_with_media', 'Repost + Media'), ('repost_quote', 'Quote Repost'), ('repost_remix', 'Remix Repost'), ('mixed', 'Mixed Media')], default='text', max_length=20),
        ),
    ]
