# Generated by Django 4.2.25 on 2025-10-14 12:24

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for media hosted elsewhere (e.g., CDN, Unsplash)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=content.models.postmedia_file_upload_to),
        ),
    ]
