# Generated by Django 4.2.25 on 2025-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_postmedia_external_url_alter_postmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_content',
            field=models.TextField(blank=True, help_text='Rich HTML content for article posts with embedded media (TipTap editor output)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Basic HTML for post captions/descriptions (supports bold, italic, links, emoji)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('video', 'Video Post'), ('audio', 'Audio Post'), ('file', 'File Post'), ('link', 'Link Post'), ('poll', 'Poll Post'), ('mixed', 'Mixed Media Post'), ('article', 'Rich Article'), ('repost', 'Simple Repost'), ('repost_with_media', 'Repost + Media'), ('repost_quote', 'Quote Repost'), ('repost_remix', 'Remix Repost')], default='text', max_length=20),
        ),
    ]
