# Generated by Django 4.2.25 on 2025-10-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_article_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short excerpt/summary for article posts (150-300 chars recommended)', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured/cover image for article posts', null=True, upload_to='post_featured_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this is a draft (not published yet)'),
        ),
    ]
