# Generated by Django 4.2.25 on 2025-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_post_excerpt_post_featured_image_post_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvotes_count',
            field=models.PositiveIntegerField(default=0, help_text='Downvotes for posts in threads'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_best_post',
            field=models.BooleanField(default=False, help_text='Marked as best post by thread creator (Q&A, solutions, etc.)'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes_count',
            field=models.PositiveIntegerField(default=0, help_text='Upvotes for posts in threads (Stack Overflow style)'),
        ),
    ]
