# Generated by Django 4.2.25 on 2025-10-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_thread_section'),
        ('content', '0009_post_downvotes_count_post_is_best_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section if posted directly (not in thread)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_posts', to='communities.section'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('upvote', '⬆️ Upvote'), ('downvote', '⬇️ Downvote'), ('like', '👍 Like'), ('love', '❤️ Love'), ('care', '🤗 Care'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('yay', '🎉 Yay'), ('clap', '👏 Clap'), ('fire', '🔥 Fire'), ('star', '⭐ Star'), ('party', '🥳 Party'), ('heart_eyes', '😍 Heart Eyes'), ('pray', '🙏 Pray'), ('strong', '💪 Strong'), ('celebrate', '🎊 Celebrate'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('worried', '😟 Worried'), ('disappointed', '😞 Disappointed'), ('thinking', '🤔 Thinking'), ('curious', '🧐 Curious'), ('shock', '😱 Shock'), ('confused', '😕 Confused')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('upvote', '⬆️ Upvote'), ('downvote', '⬇️ Downvote'), ('like', '👍 Like'), ('love', '❤️ Love'), ('care', '🤗 Care'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('yay', '🎉 Yay'), ('clap', '👏 Clap'), ('fire', '🔥 Fire'), ('star', '⭐ Star'), ('party', '🥳 Party'), ('heart_eyes', '😍 Heart Eyes'), ('pray', '🙏 Pray'), ('strong', '💪 Strong'), ('celebrate', '🎊 Celebrate'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('worried', '😟 Worried'), ('disappointed', '😞 Disappointed'), ('thinking', '🤔 Thinking'), ('curious', '🧐 Curious'), ('shock', '😱 Shock'), ('confused', '😕 Confused')], db_index=True, max_length=20),
        ),
    ]
