# Generated by Django 4.2.25 on 2025-10-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_section_unique_together_and_more'),
        ('content', '0010_post_section_alter_commentreaction_reaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.AddField(
            model_name='post',
            name='rubrique_template',
            field=models.ForeignKey(blank=True, help_text='Rubrique for direct posts (not in thread). Required if thread is null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='communities.rubriquetemplate'),
        ),
    ]
