# Generated by Django 4.2.25 on 2025-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_post_section_post_rubrique_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text="Title for article posts (required for post_type='article')", max_length=300),
        ),
    ]
