# Generated by Django 4.2.24 on 2025-09-29 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('message', 'Message'), ('new_message', 'New Message'), ('share', 'Share'), ('report', 'Report'), ('repost', 'Repost'), ('system', 'System'), ('badge', 'Badge'), ('achievement', 'Achievement'), ('warranty', 'Warranty'), ('maintenance', 'Maintenance'), ('welcome', 'Welcome'), ('security_alert', 'Security Alert'), ('digest', 'Digest'), ('community_invite', 'Community Invite'), ('community_join', 'Community Join'), ('community_post', 'Community Post'), ('community_role_change', 'Community Role Change'), ('geo_restriction', 'Geo Restriction')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Elevated'), (3, 'Normal'), (4, 'Low'), (5, 'Very Low')], default=3, help_text='Lower number = higher priority')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional context data for the notification', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry timestamp — ignored if null', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.userprofile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['content_type', 'object_id', 'notification_type'], name='notificatio_content_82a795_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
    ]
